# Generated by Django 5.1.1 on 2024-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.BinaryField(unique=True),
        ),
    ]
